sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: java
jdk: oraclejdk8

branches:
  only: master

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - sudo export XVFBARGS=":99 -screen 0 1280x1024x24 +extension RANDR +extension RENDER +extension GLX" & sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  mvn install

