sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: java
jdk: oraclejdk8

branches:
  only: master

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD/chromedriver

before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
	- "export DISPLAY=:99"

#before_script:
#  - "export DISPLAY=:99"
#  - sudo /usr/bin/Xvfb :99 -extension RANDR +extension RENDER +extension GLX &
#  - sleep 3 # give xvfb some time to start

script:
  - mvn install -Dwebdriver.gecko.driver=./geckodriver/geckodriver -Dwebdriver.chrome.driver=./chromedriver

